"""empty message

Revision ID: 9eea81a9bd7e
Revises: 
Create Date: 2023-04-30 20:50:58.415958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eea81a9bd7e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exhibiciones')
    with op.batch_alter_table('exhibicion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('puntaje_max', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exhibicion', schema=None) as batch_op:
        batch_op.drop_column('puntaje_max')

    op.create_table('exhibiciones',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('descripcion', sa.VARCHAR(length=100), nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
