"""empty message

Revision ID: 308e5337bd75
Revises: 9eea81a9bd7e
Create Date: 2023-05-03 14:58:03.804007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '308e5337bd75'
down_revision = '9eea81a9bd7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('rol', sa.String(length=10), server_default='users', nullable=False))
        batch_op.create_index(batch_op.f('ix_animal_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_animal_email'))
        batch_op.drop_column('rol')
        batch_op.drop_column('password')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
